title: Azzam Alnatsheh
logo: /assets/img/LinkedIn Image.jpg
description: ğŸ‘¨â€ğŸ’» Data & Reporting Specialist | Certified Data Scientist | SQL â€¢ SAP HANA â€¢ Power BI â€¢ Python | Driving Efficient Reporting & Insights ğŸ“Š
show_downloads: False
theme: jekyll-theme-minimal
