title: Azzam Alnatsheh
logo: /assets/img/LinkedIn Image.jpg
description: Data & Reporting Specialist â€¢ Certified Data Scientist â€¢ Data Analyst â€¢ Business Intelligence Specialist | SAP HANA â€¢ SQL â€¢ Power BI â€¢ Python | ğŸ‘¨â€ğŸ’» Turning Data into Insights ğŸ”
show_downloads: False
theme: jekyll-theme-minimal
