title: Azzam Alnatsheh
logo: /assets/img/LinkedIn Image.jpg
description: I design interactive dashboards and optimized data models in Power BI and SQL Server to help businesses make faster, data-driven decisions.
- ğŸ‘¨â€ğŸ’» Azzam Alnatsheh
- ğŸ“§ azzam-2222@live.com
- ğŸ“±Â +974 66242669
- ğŸ”— linkedin.com/in/azzamalnatsheh/
show_downloads: False
theme: jekyll-theme-minimal
